- name: Main
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "{{ansible_env.HOME}}"
    swap_size_mb: 1024
    git_user_email: "ubuntupunk@gmail.com"
    git_user_name: "ubuntupunk"
    zerotier_network_id: "272f5eae16d1da35"
    airsane_build_dir: "{{ ansible_env.HOME }}/Code/AirSane-build"
    bolt_build_dir: "{{ ansible_env.HOME }}/Code/bolt/"  
    transcrypt_build_dir: "{{ ansible_env.HOME }}/Code/transcrypt"
    radio_build_dir: "{{ ansible_env.HOME }}/Code/radio"
    dot_working_dir: "{{ ansible_env.HOME }}/Code/dotfiles"
    account: "{{ ansible_env.USER}}"
    usb_device_path: "/dev/sda1"
    usb_mount_path: "/media/usb"
 
  tasks:

    - debug:
        msg: "{{ ansible_env }}"
      tags: task1

    - debug:    
        msg: "Output of your HOME variable: {{ ansible_env.HOME }}"
      tags: task2

    - name: Setup Repos
      ansible.builtin.include_tasks:
        file: tasks/setup_repos.yml
      tags: task3
      
    - name: Initial setup
      ansible.builtin.include_tasks:
        file: tasks/initial_setup.yml
      tags: task4
    
    - name: SWAP
      ansible.builtin.include_tasks:
        file: tasks/swap.yml
      tags: task5    

    - name: GIT
      ansible.builtin.include_tasks:
        file: tasks/git.yml
      tags: task6

#    - name: SSH
#      ansible.builtin.include_tasks:
#        file: tasks/ssh.yml

    - name: ZeroTier
      ansible.builtin.include_tasks:
        file: tasks/zerotier.yml
      tags: task7

    - name: pyenv
      ansible.builtin.include_tasks:
        file: tasks/pyenv.yml
      tags: task8

    - name: Rustup
      ansible.builtin.include_tasks:
        file: tasks/rust.yml
      tags: task9

    - name: Ruby
      ansible.builtin.include_tasks:
        file: tasks/rubenv.yml     
      tags: task10

    - name: CUPS
      ansible.builtin.include_tasks:
        file: tasks/cups.yml
      tags: task11

    - name: Radio
      ansible.builtin.include_tasks:
        file: tasks/radio.yml
      tags: task12   
       
    - name: AirSane
      ansible.builtin.include_tasks:
        file: tasks/airsane.yml
      tags: task13
  
    - name: Docker
      ansible.builtin.include_tasks:
        file: tasks/docker.yml
      tags: task14

    - name: Bash Customise
      ansible.builtin.include_tasks:
        file: tasks/bash.yml
      tags: task15
   
    - name: Setup i3wm
      ansible.builtin.include_tasks:
        file: tasks/i3wmsetup.yml
      tags: task16           
        
# ========== OPTIONAL ==================

#    - name: Docker to USB
#      ansible.builtin.include_tasks:
#        file: tasks/docker_to_usb.yml

#    - name: Personal projects
#      ansible.builtin.include_tasks:
#        file: tasks/projects.yml
