- name: Download Dotfiles
  git: 
    repo: https://github.com/ubuntupunk/dotfiles
    dest: "{{ ansible_env.HOME }}/Code/dotfiles"

- name: Ensure .bash_aliases exist
  copy:
    content: ""
    dest: "{{ansible_env.HOME}}/.bash_aliases"
    force: false
    group: "{{account}}"
    owner: "{{account}}"   
    mode: 644

- name: Make sure aliases content is present in .bash_aliases
  become: true
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    block: "{{ lookup('file', '{{dot_working_dir}}/.bash_aliases') }}"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - bash'
    create: yes

#- name: Append Test lineinfile
#  ansible.builtin.lineinfile:
#    path: .bashrc
#    line: "mytest lineinfile"