- name: Setup editor
  git_config:
    name: core.editor
    scope: global
    value: vim
  tags: t16

- name: Setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  tags: t17

- name: Setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  tags: t18
