- name: Install rbenv
  become: true
  apt:
    pkg:
      - rbenv
  tags: t28

- name: Add rbenv to .bashrc
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - rbenv'
    create: yes
  tags: t29

- name: Clone latest Ruby-Build 
  git:
    repo: https://github.com/rbenv/ruby-build.git 
    dest: "{{ansible_env.HOME}}/.rbenv/plugins/ruby-build"
  tags: ruby-build
  tags: t30

- name: Install J for Jot
  become: true
  shell: "gem install j"
